import { randomUUID } from "node:crypto";
import {
  GOOGLE_HASH_OPTIONS,
  META_HASH_OPTIONS,
  computeAttributionExpiry,
  decideResolution,
  hashEmail,
  hashPhone,
  normalizeIdentity,
  scoreSpam,
  splitName,
  type IdentifierMatch,
} from "@monark/core";
import {
  consentRecords,
  leadTouchpoints,
  leads,
  personIdentifiers,
  persons,
} from "@monark/db";
import { and, eq, inArray, sql } from "drizzle-orm";
import { emitConversionEvent, eventKeyFor } from "../conversions/emit";
import type { Tx } from "../types";

export interface IngestLeadInput {
  orgId: string;
  projectId?: string | null;

  name?: string | null;
  phone?: string | null;
  email?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;

  source: string;
  sourceDetail?: string | null;

  utm?: {
    source?: string | null;
    medium?: string | null;
    campaign?: string | null;
    content?: string | null;
    term?: string | null;
    id?: string | null;
  };

  clickIds?: {
    gclid?: string | null;
    gbraid?: string | null;
    wbraid?: string | null;
    fbclid?: string | null;
    fbp?: string | null;
    fbc?: string | null;
    ctwaClid?: string | null;
    metaLeadId?: string | null;
    msclkid?: string | null;
    liFatId?: string | null;
  };

  /** Generated by the browser and shared with the Meta Pixel's Lead event so
   *  the two deduplicate. See emit.ts. */
  browserEventId?: string | null;

  landingPage?: string | null;
  referrer?: string | null;
  userAgent?: string | null;
  ipAddress?: string | null;
  /** When the ad click happened, if the caller knows. The attribution clock
   *  runs from this, not from receipt. */
  clickedAt?: Date | null;
  occurredAt?: Date | null;

  consent?: {
    marketing?: boolean;
    adUserData?: boolean;
    adPersonalization?: boolean;
    policyVersion?: string | null;
    collectedVia?: string | null;
  };

  externalId?: string | null;
  notes?: string | null;
  timeOnPageSeconds?: number | null;
  submissionsFromIpLastHour?: number;
  rawPayload?: unknown;
}

export interface IngestLeadResult {
  leadId: string;
  leadReference: string;
  personId: string;
  touchpointId: string;
  /** False when the enquiry attached to an existing open opportunity. */
  isNewLead: boolean;
  isNewPerson: boolean;
  /** Set when identifiers pointed at more than one existing person. */
  identityConflict: boolean;
  spamScore: number;
  attributionExpiresAt: Date | null;
}

/**
 * The single entry point for every inbound enquiry.
 *
 * Website forms, Meta Lead Ads webhooks, WhatsApp, portals, CSV imports and
 * manual entry all funnel through here. That is deliberate: deduplication,
 * attribution capture, consent recording and conversion emission are easy to
 * get subtly wrong, and having six code paths that each do them slightly
 * differently is how a CRM's data quality quietly rots.
 *
 * Runs entirely inside one transaction so a lead either exists complete — with
 * its person, touchpoint, consent and outbox entry — or does not exist at all.
 */
export async function ingestLead(tx: Tx, input: IngestLeadInput): Promise<IngestLeadResult> {
  const now = new Date();
  const occurredAt = input.occurredAt ?? now;

  const identity = normalizeIdentity({
    phone: input.phone,
    email: input.email,
    externalId: input.externalId,
    metaLeadId: input.clickIds?.metaLeadId,
    fullName: input.name,
  });

  const spamScore = scoreSpam({
    name: input.name,
    email: input.email,
    phone: input.phone,
    isDisposableEmail: identity.isDisposableEmail,
    isRoleAccount: identity.isRoleAccount,
    phoneValid: identity.phoneValid,
    timeOnPageSeconds: input.timeOnPageSeconds ?? null,
    submissionsFromIpLastHour: input.submissionsFromIpLastHour ?? 0,
    userAgent: input.userAgent,
  });

  // ---------------------------------------------------------------------
  // 1. Resolve identity
  // ---------------------------------------------------------------------
  const lookups: { type: "phone" | "email" | "external_id" | "meta_lead_id"; value: string }[] = [];
  if (identity.phone) lookups.push({ type: "phone", value: identity.phone.normalized });
  if (identity.email) lookups.push({ type: "email", value: identity.email.normalized });
  if (identity.externalId) lookups.push({ type: "external_id", value: identity.externalId });
  if (identity.metaLeadId) lookups.push({ type: "meta_lead_id", value: identity.metaLeadId });

  let matches: IdentifierMatch[] = [];
  if (lookups.length > 0) {
    const found = await tx
      .select({
        personId: personIdentifiers.personId,
        type: personIdentifiers.type,
        value: personIdentifiers.valueNormalized,
      })
      .from(personIdentifiers)
      .where(
        and(
          eq(personIdentifiers.orgId, input.orgId),
          inArray(
            personIdentifiers.valueNormalized,
            lookups.map((l) => l.value),
          ),
        ),
      );

    matches = found
      .filter((f) => lookups.some((l) => l.type === f.type && l.value === f.value))
      .map((f) => ({
        personId: f.personId,
        identifierType: f.type as IdentifierMatch["identifierType"],
      }));
  }

  const decision = decideResolution(matches);
  const { firstName, lastName } = splitName(input.name);

  let personId: string;
  let isNewPerson = false;

  if (decision.action === "create") {
    personId = randomUUID();
    isNewPerson = true;
    await tx.insert(persons).values({
      id: personId,
      orgId: input.orgId,
      fullName: input.name ?? null,
      firstName,
      lastName,
      primaryPhone: identity.phone?.normalized ?? null,
      primaryEmail: identity.email?.normalized ?? null,
      city: input.city ?? null,
      state: input.state ?? null,
      postalCode: input.postalCode ?? null,
      isNri: false,
    });
  } else {
    personId = decision.personId;
    // Fill gaps only. A later form where the buyer typed "Ravi" must not
    // clobber "Ravi Kumar" captured earlier.
    await tx
      .update(persons)
      .set({
        fullName: sql`COALESCE(${persons.fullName}, ${input.name ?? null})`,
        firstName: sql`COALESCE(${persons.firstName}, ${firstName})`,
        lastName: sql`COALESCE(${persons.lastName}, ${lastName})`,
        primaryEmail: sql`COALESCE(${persons.primaryEmail}, ${
          identity.email?.normalized ?? null
        })`,
        primaryPhone: sql`COALESCE(${persons.primaryPhone}, ${
          identity.phone?.normalized ?? null
        })`,
        city: sql`COALESCE(${persons.city}, ${input.city ?? null})`,
        updatedAt: now,
      })
      .where(eq(persons.id, personId));
  }

  // Attach identifiers. The unique index on (org, type, normalized value) is
  // what actually enforces deduplication under concurrent submissions — two
  // simultaneous forms with the same phone cannot create two people.
  const identifierRows = [];
  if (identity.phone) {
    identifierRows.push({
      id: randomUUID(),
      orgId: input.orgId,
      personId,
      type: "phone" as const,
      valueNormalized: identity.phone.normalized,
      valueHash: identity.phone.hash,
      valueRaw: identity.phone.raw,
    });
  }
  if (identity.email) {
    identifierRows.push({
      id: randomUUID(),
      orgId: input.orgId,
      personId,
      type: "email" as const,
      valueNormalized: identity.email.normalized,
      valueHash: identity.email.hash,
      valueRaw: identity.email.raw,
    });
  }
  if (identity.metaLeadId) {
    identifierRows.push({
      id: randomUUID(),
      orgId: input.orgId,
      personId,
      type: "meta_lead_id" as const,
      valueNormalized: identity.metaLeadId,
      valueHash: "",
      valueRaw: identity.metaLeadId,
    });
  }

  if (identifierRows.length > 0) {
    await tx
      .insert(personIdentifiers)
      .values(identifierRows)
      .onConflictDoUpdate({
        target: [
          personIdentifiers.orgId,
          personIdentifiers.type,
          personIdentifiers.valueNormalized,
        ],
        set: { lastSeenAt: now },
      });
  }

  // ---------------------------------------------------------------------
  // 2. Record consent (append-only — withdrawal is a new row, never an update)
  // ---------------------------------------------------------------------
  const consentInput = input.consent;
  if (consentInput) {
    const collectedVia = consentInput.collectedVia ?? input.landingPage ?? input.source;
    const entries: { purpose: string; granted: boolean }[] = [
      { purpose: "marketing_contact", granted: consentInput.marketing ?? false },
      { purpose: "ad_user_data", granted: consentInput.adUserData ?? false },
      { purpose: "ad_personalization", granted: consentInput.adPersonalization ?? false },
    ];

    await tx.insert(consentRecords).values(
      entries.map((e) => ({
        id: randomUUID(),
        orgId: input.orgId,
        personId,
        purpose: e.purpose,
        state: (e.granted ? "granted" : "denied") as "granted" | "denied",
        collectedVia,
        policyVersion: consentInput.policyVersion ?? null,
        ipAddress: truncateIp(input.ipAddress),
        userAgent: input.userAgent ?? null,
      })),
    );
  }

  // ---------------------------------------------------------------------
  // 3. Touchpoint — the attribution snapshot, frozen at capture
  // ---------------------------------------------------------------------
  const clickIds = input.clickIds ?? {};
  const hasGoogleClickId = Boolean(clickIds.gclid || clickIds.gbraid || clickIds.wbraid);

  const attributionExpiresAt = computeAttributionExpiry({
    clickedAt: input.clickedAt ?? null,
    occurredAt,
    hasGoogleClickId,
  });

  const touchpointId = randomUUID();
  await tx.insert(leadTouchpoints).values({
    id: touchpointId,
    orgId: input.orgId,
    personId,
    projectId: input.projectId ?? null,
    source: input.source as never,
    sourceDetail: input.sourceDetail ?? null,
    utmSource: input.utm?.source ?? null,
    utmMedium: input.utm?.medium ?? null,
    utmCampaign: input.utm?.campaign ?? null,
    utmContent: input.utm?.content ?? null,
    utmTerm: input.utm?.term ?? null,
    utmId: input.utm?.id ?? null,
    gclid: clickIds.gclid ?? null,
    gbraid: clickIds.gbraid ?? null,
    wbraid: clickIds.wbraid ?? null,
    fbclid: clickIds.fbclid ?? null,
    fbp: clickIds.fbp ?? null,
    fbc: clickIds.fbc ?? null,
    ctwaClid: clickIds.ctwaClid ?? null,
    metaLeadId: clickIds.metaLeadId ?? null,
    msclkid: clickIds.msclkid ?? null,
    liFatId: clickIds.liFatId ?? null,
    adPlatform: inferAdPlatform(clickIds, input.utm?.source),
    landingPage: input.landingPage ?? null,
    referrer: input.referrer ?? null,
    userAgent: input.userAgent ?? null,
    ipAddress: truncateIp(input.ipAddress),
    browserEventId: input.browserEventId ?? null,
    clickedAt: input.clickedAt ?? null,
    occurredAt,
    attributionExpiresAt,
    rawPayload: (input.rawPayload as never) ?? null,
  });

  // ---------------------------------------------------------------------
  // 4. Find the open opportunity, or open a new one
  // ---------------------------------------------------------------------
  const openLeads = await tx
    .select({ id: leads.id, reference: leads.reference, projectId: leads.projectId })
    .from(leads)
    .where(
      and(
        eq(leads.orgId, input.orgId),
        eq(leads.personId, personId),
        // A closed lead stays closed; a returning buyer gets a fresh
        // opportunity so the first journey's history is preserved intact.
        sql`${leads.stage} NOT IN ('booked', 'lost', 'disqualified')`,
      ),
    );

  const matchingLead = input.projectId
    ? openLeads.find((l) => l.projectId === input.projectId) ?? null
    : openLeads[0] ?? null;

  let leadId: string;
  let leadReference: string;
  let isNewLead = false;

  if (matchingLead) {
    leadId = matchingLead.id;
    leadReference = matchingLead.reference;
    await tx
      .update(leads)
      .set({ lastTouchpointId: touchpointId, lastActivityAt: now, updatedAt: now })
      .where(eq(leads.id, leadId));
  } else {
    leadId = randomUUID();
    leadReference = await nextLeadReference(tx, occurredAt);
    isNewLead = true;

    await tx.insert(leads).values({
      id: leadId,
      orgId: input.orgId,
      reference: leadReference,
      personId,
      projectId: input.projectId ?? null,
      stage: "new",
      firstTouchpointId: touchpointId,
      lastTouchpointId: touchpointId,
      lastActivityAt: now,
      spamScore,
      isTest: false,
    });
  }

  await tx
    .update(leadTouchpoints)
    .set({ leadId })
    .where(eq(leadTouchpoints.id, touchpointId));

  // ---------------------------------------------------------------------
  // 5. Emit the conversion event, in this same transaction
  // ---------------------------------------------------------------------
  if (isNewLead) {
    await emitConversionEvent(tx, {
      orgId: input.orgId,
      eventType: "lead_created",
      personId,
      leadId,
      projectId: input.projectId ?? null,
      touchpointId,
      occurredAt,
      eventKey: eventKeyFor.leadCreated(leadId, input.browserEventId),
      stageAtEvent: "new",
      sourceEntityType: "lead",
      sourceEntityId: leadId,
      attributionExpiresAt,
    });
  }

  return {
    leadId,
    leadReference,
    personId,
    touchpointId,
    isNewLead,
    isNewPerson,
    identityConflict: decision.action === "attach_with_conflict",
    spamScore,
    attributionExpiresAt,
  };
}

/** Precomputed hashes for both platforms. Google and Meta disagree on phone
 *  format, so we cannot reuse a single digest — see core/normalize/hash.ts. */
export function buildHashedIdentifiers(params: {
  email?: string | null;
  phone?: string | null;
}) {
  return {
    meta: {
      emailSha256: hashEmail(params.email, META_HASH_OPTIONS),
      phoneSha256: hashPhone(params.phone, META_HASH_OPTIONS),
    },
    google: {
      emailSha256: hashEmail(params.email, GOOGLE_HASH_OPTIONS),
      phoneSha256: hashPhone(params.phone, GOOGLE_HASH_OPTIONS),
    },
  };
}

function inferAdPlatform(
  clickIds: NonNullable<IngestLeadInput["clickIds"]>,
  utmSource?: string | null,
): string | null {
  if (clickIds.gclid || clickIds.gbraid || clickIds.wbraid) return "google";
  if (clickIds.fbclid || clickIds.ctwaClid || clickIds.metaLeadId) return "meta";
  if (clickIds.msclkid) return "bing";
  if (clickIds.liFatId) return "linkedin";

  const source = utmSource?.toLowerCase();
  if (!source) return null;
  if (source.includes("google")) return "google";
  if (source.includes("facebook") || source.includes("meta") || source.includes("instagram")) {
    return "meta";
  }
  return null;
}

/**
 * Truncate IPv4 to /24 and IPv6 to /48 before storage.
 *
 * Enough to investigate a burst of spam submissions; not enough to function as
 * a durable tracking identifier for an individual. Meta accepts a client IP to
 * improve match quality, and this keeps that useful while limiting what we
 * retain about people who never became customers.
 */
function truncateIp(ip?: string | null): string | null {
  if (!ip) return null;
  const trimmed = ip.trim();
  if (!trimmed) return null;

  if (trimmed.includes(":")) {
    const groups = trimmed.split(":");
    return `${groups.slice(0, 3).join(":")}::`;
  }
  const octets = trimmed.split(".");
  if (octets.length !== 4) return null;
  return `${octets[0]}.${octets[1]}.${octets[2]}.0`;
}

/**
 * Human-facing reference: LD-2026-008321.
 *
 * Backed by a Postgres sequence rather than a count, because a count is racy
 * under concurrent inserts and salespeople quote these numbers on live calls.
 */
async function nextLeadReference(tx: Tx, at: Date): Promise<string> {
  const result = await tx.execute(sql`SELECT nextval('lead_reference_seq') AS value`);
  const rows = result.rows as { value: string | number }[];
  const value = Number(rows[0]?.value ?? 1);
  return `LD-${at.getUTCFullYear()}-${String(value).padStart(6, "0")}`;
}
